---@meta
---@class ZoneOptions
---@field freeRepair string[]? -- Array of jobs that can repair vehicles for free
---@field freeMods string[]? -- Array of jobs that can modify vehicles for free
---@field job string[]? -- Array of jobs that can access the zone
---@field hideBlip boolean? -- Hide the blip on the map
---@field points vector3[] -- Array of points that make up the zone